theme = "base16_transparent"

[editor]
scrolloff = 8
bufferline = "multiple"
true-color = true
line-number = "relative"
mouse = false

[editor.lsp]
display-inlay-hints = true

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"
nbsp = "none"
tabpad = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = true
character = "⸽" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
